# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import starrez_client
from starrez_client.models.sdas_charge_rate_item import SDASChargeRateItem  # noqa: E501
from starrez_client.rest import ApiException


class TestSDASChargeRateItem(unittest.TestCase):
    """SDASChargeRateItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSDASChargeRateItem(self):
        """Test SDASChargeRateItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = starrez_client.models.sdas_charge_rate_item.SDASChargeRateItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
