# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import starrez_client
from starrez_client.models.portal_activity_item import PortalActivityItem  # noqa: E501
from starrez_client.rest import ApiException


class TestPortalActivityItem(unittest.TestCase):
    """PortalActivityItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPortalActivityItem(self):
        """Test PortalActivityItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = starrez_client.models.portal_activity_item.PortalActivityItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
