#!/bin/bash

test=false
gen=false
while getopts ":gct" opt
do
    case "$opt" in
        "g")
            gen=true
            ;;
        "t")
            test=true
            ;;
        "?")
            echo "Unknown option $OPTARG"
            ;;
    esac
done

if [ "$gen" = true ]
then
    cd swagger-definitions
    python3 swag-gen.py
    cd ../
fi

cd swagger-definitions
multi-file-swagger -o yaml index.yaml > ../StarRez.yaml
swagger-codegen generate -i ../StarRez.yaml -l python -o ../ -c config.json &> /dev/null
cd ../

if [ "$test" = true ]
then
    pip uninstall --yes StarRezAPI
    pip install ./
    python testClient/test.py
fi