#!/bin/bash

test=false
clean=false
gen=false
while getopts ":gct" opt
do
    case "$opt" in
        "g")
            gen=true
            ;;
        "c")
            clean=true
            ;;
        "t")
            test=true
            ;;
        "?")
            echo "Unknown option $OPTARG"
            ;;
    esac
done

if [ "$gen" = true ]
then
    cd swagger-definitions
    python3 swag-gen.py
    cd ../
fi

if [ "$clean" = true ]
then
    rm -rf ./StarRezAPI
fi

cd swagger-definitions
multi-file-swagger -o yaml index.yaml > ../StarRez.yaml
swagger-codegen generate -i ../StarRez.yaml -l python -o ../StarRezAPI -c config.json
cd ../

if [ "$test" = true ]
then
    pip uninstall --yes StarRezAPI
    pip install ./StarRezAPI
    python testClient/test.py
fi