type: object
#required:
properties:
  EntryApplicationPreferenceID:
    type: integer
    format: int32
    description: Entry Application Preference
  EntryApplicationID:
    type: integer
    format: int32
    description: Entry Application
  PreferenceID:
    type: integer
    format: int32
    description: Preference
  Preference:
    type: string
    format: byte
    description: Preference
  Comments:
    type: string
    maxLength: 1000
    description: Comments
  DateModified:
    type: string
    format: datetimeseconds
    description: Date Modified
