type: object
#required:
properties:
  InterfaceApplicationID:
    type: integer
    format: int32
    description: Interface Application
  RecordTypeEnum:
    type: string
    format: enum
    description: Record Type
  Description:
    type: string
    maxLength: 25
    description: Description
  Comments:
    type: string
    maxLength: 100
    description: Comments
  DateModified:
    type: string
    format: datetimeseconds
    description: Date Modified
