type: object
#required:
properties:
  MessageSubscriptionSettingsID:
    type: integer
    format: int32
    description: Message Subscription Settings
  MessageSubscriptionID:
    type: integer
    format: int32
    description: Message Subscription
  SettingName:
    type: string
    maxLength: 50
    description: Setting Name
  SettingValue:
    type: string
    format: longstring
    description: Setting Value
  SecurityUserID:
    type: integer
    format: int32
    description: Security User
  DateCreated:
    type: string
    format: date-time
    description: Date Created
  DateModified:
    type: string
    format: datetimeseconds
    description: Date Modified
