type: object
#required:
#  - Description
properties:
  RefundRequestBatchConfigurationID:
    type: integer
    format: int32
    description: Refund Request Batch Configuration
  DynamicListID:
    type: integer
    format: int32
    description: Dynamic List
  Description:
    type: string
    maxLength: 200
    description: Description
  Comments:
    type: string
    maxLength: 300
    description: Comments
  SecurityUserID:
    type: integer
    format: int32
    description: Security User
  CreatedBy_SecurityUserID:
    type: integer
    format: int32
    description: Created By Security User
  DateCreated:
    type: string
    format: date-time
    description: Date Created
  RecordTypeEnum:
    type: string
    format: enum
    description: Record Type
  DateModified:
    type: string
    format: datetimeseconds
    description: Date Modified
