# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BookingAgreementItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'booking_agreement_id': 'int',
        'booking_id': 'int',
        'table_name': 'str',
        'table_id': 'int',
        'date_agreed': 'str',
        'date_modified': 'str'
    }

    attribute_map = {
        'booking_agreement_id': 'BookingAgreementID',
        'booking_id': 'BookingID',
        'table_name': 'TableName',
        'table_id': 'TableID',
        'date_agreed': 'DateAgreed',
        'date_modified': 'DateModified'
    }

    def __init__(self, booking_agreement_id=None, booking_id=None, table_name=None, table_id=None, date_agreed=None, date_modified=None):  # noqa: E501
        """BookingAgreementItem - a model defined in Swagger"""  # noqa: E501

        self._booking_agreement_id = None
        self._booking_id = None
        self._table_name = None
        self._table_id = None
        self._date_agreed = None
        self._date_modified = None
        self.discriminator = None

        if booking_agreement_id is not None:
            self.booking_agreement_id = booking_agreement_id
        if booking_id is not None:
            self.booking_id = booking_id
        if table_name is not None:
            self.table_name = table_name
        if table_id is not None:
            self.table_id = table_id
        if date_agreed is not None:
            self.date_agreed = date_agreed
        if date_modified is not None:
            self.date_modified = date_modified

    @property
    def booking_agreement_id(self):
        """Gets the booking_agreement_id of this BookingAgreementItem.  # noqa: E501

        Booking Agreement  # noqa: E501

        :return: The booking_agreement_id of this BookingAgreementItem.  # noqa: E501
        :rtype: int
        """
        return self._booking_agreement_id

    @booking_agreement_id.setter
    def booking_agreement_id(self, booking_agreement_id):
        """Sets the booking_agreement_id of this BookingAgreementItem.

        Booking Agreement  # noqa: E501

        :param booking_agreement_id: The booking_agreement_id of this BookingAgreementItem.  # noqa: E501
        :type: int
        """

        self._booking_agreement_id = booking_agreement_id

    @property
    def booking_id(self):
        """Gets the booking_id of this BookingAgreementItem.  # noqa: E501

        Booking  # noqa: E501

        :return: The booking_id of this BookingAgreementItem.  # noqa: E501
        :rtype: int
        """
        return self._booking_id

    @booking_id.setter
    def booking_id(self, booking_id):
        """Sets the booking_id of this BookingAgreementItem.

        Booking  # noqa: E501

        :param booking_id: The booking_id of this BookingAgreementItem.  # noqa: E501
        :type: int
        """

        self._booking_id = booking_id

    @property
    def table_name(self):
        """Gets the table_name of this BookingAgreementItem.  # noqa: E501

        Table Name  # noqa: E501

        :return: The table_name of this BookingAgreementItem.  # noqa: E501
        :rtype: str
        """
        return self._table_name

    @table_name.setter
    def table_name(self, table_name):
        """Sets the table_name of this BookingAgreementItem.

        Table Name  # noqa: E501

        :param table_name: The table_name of this BookingAgreementItem.  # noqa: E501
        :type: str
        """
        if table_name is not None and len(table_name) > 50:
            raise ValueError("Invalid value for `table_name`, length must be less than or equal to `50`")  # noqa: E501

        self._table_name = table_name

    @property
    def table_id(self):
        """Gets the table_id of this BookingAgreementItem.  # noqa: E501

        Table  # noqa: E501

        :return: The table_id of this BookingAgreementItem.  # noqa: E501
        :rtype: int
        """
        return self._table_id

    @table_id.setter
    def table_id(self, table_id):
        """Sets the table_id of this BookingAgreementItem.

        Table  # noqa: E501

        :param table_id: The table_id of this BookingAgreementItem.  # noqa: E501
        :type: int
        """

        self._table_id = table_id

    @property
    def date_agreed(self):
        """Gets the date_agreed of this BookingAgreementItem.  # noqa: E501

        Date Agreed  # noqa: E501

        :return: The date_agreed of this BookingAgreementItem.  # noqa: E501
        :rtype: str
        """
        return self._date_agreed

    @date_agreed.setter
    def date_agreed(self, date_agreed):
        """Sets the date_agreed of this BookingAgreementItem.

        Date Agreed  # noqa: E501

        :param date_agreed: The date_agreed of this BookingAgreementItem.  # noqa: E501
        :type: str
        """

        self._date_agreed = date_agreed

    @property
    def date_modified(self):
        """Gets the date_modified of this BookingAgreementItem.  # noqa: E501

        Date Modified  # noqa: E501

        :return: The date_modified of this BookingAgreementItem.  # noqa: E501
        :rtype: str
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this BookingAgreementItem.

        Date Modified  # noqa: E501

        :param date_modified: The date_modified of this BookingAgreementItem.  # noqa: E501
        :type: str
        """

        self._date_modified = date_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BookingAgreementItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
