# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DashboardSharingItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dashboard_sharing_id': 'int',
        'security_group_id': 'int',
        'dashboard_id': 'int',
        'date_modified': 'str'
    }

    attribute_map = {
        'dashboard_sharing_id': 'DashboardSharingID',
        'security_group_id': 'SecurityGroupID',
        'dashboard_id': 'DashboardID',
        'date_modified': 'DateModified'
    }

    def __init__(self, dashboard_sharing_id=None, security_group_id=None, dashboard_id=None, date_modified=None):  # noqa: E501
        """DashboardSharingItem - a model defined in Swagger"""  # noqa: E501

        self._dashboard_sharing_id = None
        self._security_group_id = None
        self._dashboard_id = None
        self._date_modified = None
        self.discriminator = None

        if dashboard_sharing_id is not None:
            self.dashboard_sharing_id = dashboard_sharing_id
        if security_group_id is not None:
            self.security_group_id = security_group_id
        if dashboard_id is not None:
            self.dashboard_id = dashboard_id
        if date_modified is not None:
            self.date_modified = date_modified

    @property
    def dashboard_sharing_id(self):
        """Gets the dashboard_sharing_id of this DashboardSharingItem.  # noqa: E501

        Dashboard Sharing  # noqa: E501

        :return: The dashboard_sharing_id of this DashboardSharingItem.  # noqa: E501
        :rtype: int
        """
        return self._dashboard_sharing_id

    @dashboard_sharing_id.setter
    def dashboard_sharing_id(self, dashboard_sharing_id):
        """Sets the dashboard_sharing_id of this DashboardSharingItem.

        Dashboard Sharing  # noqa: E501

        :param dashboard_sharing_id: The dashboard_sharing_id of this DashboardSharingItem.  # noqa: E501
        :type: int
        """

        self._dashboard_sharing_id = dashboard_sharing_id

    @property
    def security_group_id(self):
        """Gets the security_group_id of this DashboardSharingItem.  # noqa: E501

        Security Group  # noqa: E501

        :return: The security_group_id of this DashboardSharingItem.  # noqa: E501
        :rtype: int
        """
        return self._security_group_id

    @security_group_id.setter
    def security_group_id(self, security_group_id):
        """Sets the security_group_id of this DashboardSharingItem.

        Security Group  # noqa: E501

        :param security_group_id: The security_group_id of this DashboardSharingItem.  # noqa: E501
        :type: int
        """

        self._security_group_id = security_group_id

    @property
    def dashboard_id(self):
        """Gets the dashboard_id of this DashboardSharingItem.  # noqa: E501

        Dashboard  # noqa: E501

        :return: The dashboard_id of this DashboardSharingItem.  # noqa: E501
        :rtype: int
        """
        return self._dashboard_id

    @dashboard_id.setter
    def dashboard_id(self, dashboard_id):
        """Sets the dashboard_id of this DashboardSharingItem.

        Dashboard  # noqa: E501

        :param dashboard_id: The dashboard_id of this DashboardSharingItem.  # noqa: E501
        :type: int
        """

        self._dashboard_id = dashboard_id

    @property
    def date_modified(self):
        """Gets the date_modified of this DashboardSharingItem.  # noqa: E501

        Date Modified  # noqa: E501

        :return: The date_modified of this DashboardSharingItem.  # noqa: E501
        :rtype: str
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this DashboardSharingItem.

        Date Modified  # noqa: E501

        :param date_modified: The date_modified of this DashboardSharingItem.  # noqa: E501
        :type: str
        """

        self._date_modified = date_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DashboardSharingItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
