# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DashboardPanelSettingItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dashboard_panel_setting_id': 'int',
        'dashboard_panel_id': 'int',
        'setting_name': 'str',
        'setting_value': 'str',
        'date_modified': 'str'
    }

    attribute_map = {
        'dashboard_panel_setting_id': 'DashboardPanelSettingID',
        'dashboard_panel_id': 'DashboardPanelID',
        'setting_name': 'SettingName',
        'setting_value': 'SettingValue',
        'date_modified': 'DateModified'
    }

    def __init__(self, dashboard_panel_setting_id=None, dashboard_panel_id=None, setting_name=None, setting_value=None, date_modified=None):  # noqa: E501
        """DashboardPanelSettingItem - a model defined in Swagger"""  # noqa: E501

        self._dashboard_panel_setting_id = None
        self._dashboard_panel_id = None
        self._setting_name = None
        self._setting_value = None
        self._date_modified = None
        self.discriminator = None

        if dashboard_panel_setting_id is not None:
            self.dashboard_panel_setting_id = dashboard_panel_setting_id
        if dashboard_panel_id is not None:
            self.dashboard_panel_id = dashboard_panel_id
        if setting_name is not None:
            self.setting_name = setting_name
        if setting_value is not None:
            self.setting_value = setting_value
        if date_modified is not None:
            self.date_modified = date_modified

    @property
    def dashboard_panel_setting_id(self):
        """Gets the dashboard_panel_setting_id of this DashboardPanelSettingItem.  # noqa: E501

        Dashboard Panel Setting  # noqa: E501

        :return: The dashboard_panel_setting_id of this DashboardPanelSettingItem.  # noqa: E501
        :rtype: int
        """
        return self._dashboard_panel_setting_id

    @dashboard_panel_setting_id.setter
    def dashboard_panel_setting_id(self, dashboard_panel_setting_id):
        """Sets the dashboard_panel_setting_id of this DashboardPanelSettingItem.

        Dashboard Panel Setting  # noqa: E501

        :param dashboard_panel_setting_id: The dashboard_panel_setting_id of this DashboardPanelSettingItem.  # noqa: E501
        :type: int
        """

        self._dashboard_panel_setting_id = dashboard_panel_setting_id

    @property
    def dashboard_panel_id(self):
        """Gets the dashboard_panel_id of this DashboardPanelSettingItem.  # noqa: E501

        Dashboard Panel  # noqa: E501

        :return: The dashboard_panel_id of this DashboardPanelSettingItem.  # noqa: E501
        :rtype: int
        """
        return self._dashboard_panel_id

    @dashboard_panel_id.setter
    def dashboard_panel_id(self, dashboard_panel_id):
        """Sets the dashboard_panel_id of this DashboardPanelSettingItem.

        Dashboard Panel  # noqa: E501

        :param dashboard_panel_id: The dashboard_panel_id of this DashboardPanelSettingItem.  # noqa: E501
        :type: int
        """

        self._dashboard_panel_id = dashboard_panel_id

    @property
    def setting_name(self):
        """Gets the setting_name of this DashboardPanelSettingItem.  # noqa: E501

        Setting Name  # noqa: E501

        :return: The setting_name of this DashboardPanelSettingItem.  # noqa: E501
        :rtype: str
        """
        return self._setting_name

    @setting_name.setter
    def setting_name(self, setting_name):
        """Sets the setting_name of this DashboardPanelSettingItem.

        Setting Name  # noqa: E501

        :param setting_name: The setting_name of this DashboardPanelSettingItem.  # noqa: E501
        :type: str
        """
        if setting_name is not None and len(setting_name) > 250:
            raise ValueError("Invalid value for `setting_name`, length must be less than or equal to `250`")  # noqa: E501

        self._setting_name = setting_name

    @property
    def setting_value(self):
        """Gets the setting_value of this DashboardPanelSettingItem.  # noqa: E501

        Setting Value  # noqa: E501

        :return: The setting_value of this DashboardPanelSettingItem.  # noqa: E501
        :rtype: str
        """
        return self._setting_value

    @setting_value.setter
    def setting_value(self, setting_value):
        """Sets the setting_value of this DashboardPanelSettingItem.

        Setting Value  # noqa: E501

        :param setting_value: The setting_value of this DashboardPanelSettingItem.  # noqa: E501
        :type: str
        """

        self._setting_value = setting_value

    @property
    def date_modified(self):
        """Gets the date_modified of this DashboardPanelSettingItem.  # noqa: E501

        Date Modified  # noqa: E501

        :return: The date_modified of this DashboardPanelSettingItem.  # noqa: E501
        :rtype: str
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this DashboardPanelSettingItem.

        Date Modified  # noqa: E501

        :param date_modified: The date_modified of this DashboardPanelSettingItem.  # noqa: E501
        :type: str
        """

        self._date_modified = date_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DashboardPanelSettingItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
