# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EntryElectronicIdentityItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entry_electronic_identity_id': 'int',
        'entry_id': 'int',
        'electronic_identity_type_id': 'int',
        'electronic_identity': 'str',
        'date_modified': 'str'
    }

    attribute_map = {
        'entry_electronic_identity_id': 'EntryElectronicIdentityID',
        'entry_id': 'EntryID',
        'electronic_identity_type_id': 'ElectronicIdentityTypeID',
        'electronic_identity': 'ElectronicIdentity',
        'date_modified': 'DateModified'
    }

    def __init__(self, entry_electronic_identity_id=None, entry_id=None, electronic_identity_type_id=None, electronic_identity=None, date_modified=None):  # noqa: E501
        """EntryElectronicIdentityItem - a model defined in Swagger"""  # noqa: E501

        self._entry_electronic_identity_id = None
        self._entry_id = None
        self._electronic_identity_type_id = None
        self._electronic_identity = None
        self._date_modified = None
        self.discriminator = None

        if entry_electronic_identity_id is not None:
            self.entry_electronic_identity_id = entry_electronic_identity_id
        if entry_id is not None:
            self.entry_id = entry_id
        if electronic_identity_type_id is not None:
            self.electronic_identity_type_id = electronic_identity_type_id
        if electronic_identity is not None:
            self.electronic_identity = electronic_identity
        if date_modified is not None:
            self.date_modified = date_modified

    @property
    def entry_electronic_identity_id(self):
        """Gets the entry_electronic_identity_id of this EntryElectronicIdentityItem.  # noqa: E501

        Entry Electronic Identity  # noqa: E501

        :return: The entry_electronic_identity_id of this EntryElectronicIdentityItem.  # noqa: E501
        :rtype: int
        """
        return self._entry_electronic_identity_id

    @entry_electronic_identity_id.setter
    def entry_electronic_identity_id(self, entry_electronic_identity_id):
        """Sets the entry_electronic_identity_id of this EntryElectronicIdentityItem.

        Entry Electronic Identity  # noqa: E501

        :param entry_electronic_identity_id: The entry_electronic_identity_id of this EntryElectronicIdentityItem.  # noqa: E501
        :type: int
        """

        self._entry_electronic_identity_id = entry_electronic_identity_id

    @property
    def entry_id(self):
        """Gets the entry_id of this EntryElectronicIdentityItem.  # noqa: E501

        Entry  # noqa: E501

        :return: The entry_id of this EntryElectronicIdentityItem.  # noqa: E501
        :rtype: int
        """
        return self._entry_id

    @entry_id.setter
    def entry_id(self, entry_id):
        """Sets the entry_id of this EntryElectronicIdentityItem.

        Entry  # noqa: E501

        :param entry_id: The entry_id of this EntryElectronicIdentityItem.  # noqa: E501
        :type: int
        """

        self._entry_id = entry_id

    @property
    def electronic_identity_type_id(self):
        """Gets the electronic_identity_type_id of this EntryElectronicIdentityItem.  # noqa: E501

        Electronic Identity Type  # noqa: E501

        :return: The electronic_identity_type_id of this EntryElectronicIdentityItem.  # noqa: E501
        :rtype: int
        """
        return self._electronic_identity_type_id

    @electronic_identity_type_id.setter
    def electronic_identity_type_id(self, electronic_identity_type_id):
        """Sets the electronic_identity_type_id of this EntryElectronicIdentityItem.

        Electronic Identity Type  # noqa: E501

        :param electronic_identity_type_id: The electronic_identity_type_id of this EntryElectronicIdentityItem.  # noqa: E501
        :type: int
        """

        self._electronic_identity_type_id = electronic_identity_type_id

    @property
    def electronic_identity(self):
        """Gets the electronic_identity of this EntryElectronicIdentityItem.  # noqa: E501

        Electronic Identity  # noqa: E501

        :return: The electronic_identity of this EntryElectronicIdentityItem.  # noqa: E501
        :rtype: str
        """
        return self._electronic_identity

    @electronic_identity.setter
    def electronic_identity(self, electronic_identity):
        """Sets the electronic_identity of this EntryElectronicIdentityItem.

        Electronic Identity  # noqa: E501

        :param electronic_identity: The electronic_identity of this EntryElectronicIdentityItem.  # noqa: E501
        :type: str
        """
        if electronic_identity is not None and len(electronic_identity) > 500:
            raise ValueError("Invalid value for `electronic_identity`, length must be less than or equal to `500`")  # noqa: E501

        self._electronic_identity = electronic_identity

    @property
    def date_modified(self):
        """Gets the date_modified of this EntryElectronicIdentityItem.  # noqa: E501

        Date Modified  # noqa: E501

        :return: The date_modified of this EntryElectronicIdentityItem.  # noqa: E501
        :rtype: str
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this EntryElectronicIdentityItem.

        Date Modified  # noqa: E501

        :param date_modified: The date_modified of this EntryElectronicIdentityItem.  # noqa: E501
        :type: str
        """

        self._date_modified = date_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EntryElectronicIdentityItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
