# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EntryApplicationPortalSectionItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entry_application_portal_section_id': 'int',
        'web_section_id': 'int',
        'entry_application_id': 'int',
        'complete': 'bool',
        'complete_date': 'str',
        'date_created': 'datetime',
        'date_modified': 'str'
    }

    attribute_map = {
        'entry_application_portal_section_id': 'EntryApplicationPortalSectionID',
        'web_section_id': 'WebSectionID',
        'entry_application_id': 'EntryApplicationID',
        'complete': 'Complete',
        'complete_date': 'CompleteDate',
        'date_created': 'DateCreated',
        'date_modified': 'DateModified'
    }

    def __init__(self, entry_application_portal_section_id=None, web_section_id=None, entry_application_id=None, complete=None, complete_date=None, date_created=None, date_modified=None):  # noqa: E501
        """EntryApplicationPortalSectionItem - a model defined in Swagger"""  # noqa: E501

        self._entry_application_portal_section_id = None
        self._web_section_id = None
        self._entry_application_id = None
        self._complete = None
        self._complete_date = None
        self._date_created = None
        self._date_modified = None
        self.discriminator = None

        if entry_application_portal_section_id is not None:
            self.entry_application_portal_section_id = entry_application_portal_section_id
        if web_section_id is not None:
            self.web_section_id = web_section_id
        if entry_application_id is not None:
            self.entry_application_id = entry_application_id
        if complete is not None:
            self.complete = complete
        if complete_date is not None:
            self.complete_date = complete_date
        if date_created is not None:
            self.date_created = date_created
        if date_modified is not None:
            self.date_modified = date_modified

    @property
    def entry_application_portal_section_id(self):
        """Gets the entry_application_portal_section_id of this EntryApplicationPortalSectionItem.  # noqa: E501

        Entry Application Portal Section  # noqa: E501

        :return: The entry_application_portal_section_id of this EntryApplicationPortalSectionItem.  # noqa: E501
        :rtype: int
        """
        return self._entry_application_portal_section_id

    @entry_application_portal_section_id.setter
    def entry_application_portal_section_id(self, entry_application_portal_section_id):
        """Sets the entry_application_portal_section_id of this EntryApplicationPortalSectionItem.

        Entry Application Portal Section  # noqa: E501

        :param entry_application_portal_section_id: The entry_application_portal_section_id of this EntryApplicationPortalSectionItem.  # noqa: E501
        :type: int
        """

        self._entry_application_portal_section_id = entry_application_portal_section_id

    @property
    def web_section_id(self):
        """Gets the web_section_id of this EntryApplicationPortalSectionItem.  # noqa: E501

        Web Section  # noqa: E501

        :return: The web_section_id of this EntryApplicationPortalSectionItem.  # noqa: E501
        :rtype: int
        """
        return self._web_section_id

    @web_section_id.setter
    def web_section_id(self, web_section_id):
        """Sets the web_section_id of this EntryApplicationPortalSectionItem.

        Web Section  # noqa: E501

        :param web_section_id: The web_section_id of this EntryApplicationPortalSectionItem.  # noqa: E501
        :type: int
        """

        self._web_section_id = web_section_id

    @property
    def entry_application_id(self):
        """Gets the entry_application_id of this EntryApplicationPortalSectionItem.  # noqa: E501

        Entry Application  # noqa: E501

        :return: The entry_application_id of this EntryApplicationPortalSectionItem.  # noqa: E501
        :rtype: int
        """
        return self._entry_application_id

    @entry_application_id.setter
    def entry_application_id(self, entry_application_id):
        """Sets the entry_application_id of this EntryApplicationPortalSectionItem.

        Entry Application  # noqa: E501

        :param entry_application_id: The entry_application_id of this EntryApplicationPortalSectionItem.  # noqa: E501
        :type: int
        """

        self._entry_application_id = entry_application_id

    @property
    def complete(self):
        """Gets the complete of this EntryApplicationPortalSectionItem.  # noqa: E501

        Complete  # noqa: E501

        :return: The complete of this EntryApplicationPortalSectionItem.  # noqa: E501
        :rtype: bool
        """
        return self._complete

    @complete.setter
    def complete(self, complete):
        """Sets the complete of this EntryApplicationPortalSectionItem.

        Complete  # noqa: E501

        :param complete: The complete of this EntryApplicationPortalSectionItem.  # noqa: E501
        :type: bool
        """

        self._complete = complete

    @property
    def complete_date(self):
        """Gets the complete_date of this EntryApplicationPortalSectionItem.  # noqa: E501

        Complete Date  # noqa: E501

        :return: The complete_date of this EntryApplicationPortalSectionItem.  # noqa: E501
        :rtype: str
        """
        return self._complete_date

    @complete_date.setter
    def complete_date(self, complete_date):
        """Sets the complete_date of this EntryApplicationPortalSectionItem.

        Complete Date  # noqa: E501

        :param complete_date: The complete_date of this EntryApplicationPortalSectionItem.  # noqa: E501
        :type: str
        """

        self._complete_date = complete_date

    @property
    def date_created(self):
        """Gets the date_created of this EntryApplicationPortalSectionItem.  # noqa: E501

        Date Created  # noqa: E501

        :return: The date_created of this EntryApplicationPortalSectionItem.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this EntryApplicationPortalSectionItem.

        Date Created  # noqa: E501

        :param date_created: The date_created of this EntryApplicationPortalSectionItem.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def date_modified(self):
        """Gets the date_modified of this EntryApplicationPortalSectionItem.  # noqa: E501

        Date Modified  # noqa: E501

        :return: The date_modified of this EntryApplicationPortalSectionItem.  # noqa: E501
        :rtype: str
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this EntryApplicationPortalSectionItem.

        Date Modified  # noqa: E501

        :param date_modified: The date_modified of this EntryApplicationPortalSectionItem.  # noqa: E501
        :type: str
        """

        self._date_modified = date_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EntryApplicationPortalSectionItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
