# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GroupRoomSpaceItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'group_room_space_id': 'int',
        'group_id': 'int',
        'room_space_id': 'int',
        'security_user_id': 'int',
        'created_by_security_user_id': 'int',
        'date_created': 'datetime',
        'date_modified': 'str'
    }

    attribute_map = {
        'group_room_space_id': 'GroupRoomSpaceID',
        'group_id': 'GroupID',
        'room_space_id': 'RoomSpaceID',
        'security_user_id': 'SecurityUserID',
        'created_by_security_user_id': 'CreatedBy_SecurityUserID',
        'date_created': 'DateCreated',
        'date_modified': 'DateModified'
    }

    def __init__(self, group_room_space_id=None, group_id=None, room_space_id=None, security_user_id=None, created_by_security_user_id=None, date_created=None, date_modified=None):  # noqa: E501
        """GroupRoomSpaceItem - a model defined in Swagger"""  # noqa: E501

        self._group_room_space_id = None
        self._group_id = None
        self._room_space_id = None
        self._security_user_id = None
        self._created_by_security_user_id = None
        self._date_created = None
        self._date_modified = None
        self.discriminator = None

        if group_room_space_id is not None:
            self.group_room_space_id = group_room_space_id
        if group_id is not None:
            self.group_id = group_id
        if room_space_id is not None:
            self.room_space_id = room_space_id
        if security_user_id is not None:
            self.security_user_id = security_user_id
        if created_by_security_user_id is not None:
            self.created_by_security_user_id = created_by_security_user_id
        if date_created is not None:
            self.date_created = date_created
        if date_modified is not None:
            self.date_modified = date_modified

    @property
    def group_room_space_id(self):
        """Gets the group_room_space_id of this GroupRoomSpaceItem.  # noqa: E501

        Group Room Space  # noqa: E501

        :return: The group_room_space_id of this GroupRoomSpaceItem.  # noqa: E501
        :rtype: int
        """
        return self._group_room_space_id

    @group_room_space_id.setter
    def group_room_space_id(self, group_room_space_id):
        """Sets the group_room_space_id of this GroupRoomSpaceItem.

        Group Room Space  # noqa: E501

        :param group_room_space_id: The group_room_space_id of this GroupRoomSpaceItem.  # noqa: E501
        :type: int
        """

        self._group_room_space_id = group_room_space_id

    @property
    def group_id(self):
        """Gets the group_id of this GroupRoomSpaceItem.  # noqa: E501

        Group  # noqa: E501

        :return: The group_id of this GroupRoomSpaceItem.  # noqa: E501
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this GroupRoomSpaceItem.

        Group  # noqa: E501

        :param group_id: The group_id of this GroupRoomSpaceItem.  # noqa: E501
        :type: int
        """

        self._group_id = group_id

    @property
    def room_space_id(self):
        """Gets the room_space_id of this GroupRoomSpaceItem.  # noqa: E501

        Room Space  # noqa: E501

        :return: The room_space_id of this GroupRoomSpaceItem.  # noqa: E501
        :rtype: int
        """
        return self._room_space_id

    @room_space_id.setter
    def room_space_id(self, room_space_id):
        """Sets the room_space_id of this GroupRoomSpaceItem.

        Room Space  # noqa: E501

        :param room_space_id: The room_space_id of this GroupRoomSpaceItem.  # noqa: E501
        :type: int
        """

        self._room_space_id = room_space_id

    @property
    def security_user_id(self):
        """Gets the security_user_id of this GroupRoomSpaceItem.  # noqa: E501

        Security User  # noqa: E501

        :return: The security_user_id of this GroupRoomSpaceItem.  # noqa: E501
        :rtype: int
        """
        return self._security_user_id

    @security_user_id.setter
    def security_user_id(self, security_user_id):
        """Sets the security_user_id of this GroupRoomSpaceItem.

        Security User  # noqa: E501

        :param security_user_id: The security_user_id of this GroupRoomSpaceItem.  # noqa: E501
        :type: int
        """

        self._security_user_id = security_user_id

    @property
    def created_by_security_user_id(self):
        """Gets the created_by_security_user_id of this GroupRoomSpaceItem.  # noqa: E501

        Created By Security User  # noqa: E501

        :return: The created_by_security_user_id of this GroupRoomSpaceItem.  # noqa: E501
        :rtype: int
        """
        return self._created_by_security_user_id

    @created_by_security_user_id.setter
    def created_by_security_user_id(self, created_by_security_user_id):
        """Sets the created_by_security_user_id of this GroupRoomSpaceItem.

        Created By Security User  # noqa: E501

        :param created_by_security_user_id: The created_by_security_user_id of this GroupRoomSpaceItem.  # noqa: E501
        :type: int
        """

        self._created_by_security_user_id = created_by_security_user_id

    @property
    def date_created(self):
        """Gets the date_created of this GroupRoomSpaceItem.  # noqa: E501

        Date Created  # noqa: E501

        :return: The date_created of this GroupRoomSpaceItem.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this GroupRoomSpaceItem.

        Date Created  # noqa: E501

        :param date_created: The date_created of this GroupRoomSpaceItem.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def date_modified(self):
        """Gets the date_modified of this GroupRoomSpaceItem.  # noqa: E501

        Date Modified  # noqa: E501

        :return: The date_modified of this GroupRoomSpaceItem.  # noqa: E501
        :rtype: str
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this GroupRoomSpaceItem.

        Date Modified  # noqa: E501

        :param date_modified: The date_modified of this GroupRoomSpaceItem.  # noqa: E501
        :type: str
        """

        self._date_modified = date_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupRoomSpaceItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
