# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MealPlanFreeItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'meal_plan_free_id': 'int',
        'record_type_enum': 'str',
        'meal_plan_id': 'int',
        'date_start': 'str',
        'date_end': 'str',
        'date_modified': 'str'
    }

    attribute_map = {
        'meal_plan_free_id': 'MealPlanFreeID',
        'record_type_enum': 'RecordTypeEnum',
        'meal_plan_id': 'MealPlanID',
        'date_start': 'DateStart',
        'date_end': 'DateEnd',
        'date_modified': 'DateModified'
    }

    def __init__(self, meal_plan_free_id=None, record_type_enum=None, meal_plan_id=None, date_start=None, date_end=None, date_modified=None):  # noqa: E501
        """MealPlanFreeItem - a model defined in Swagger"""  # noqa: E501

        self._meal_plan_free_id = None
        self._record_type_enum = None
        self._meal_plan_id = None
        self._date_start = None
        self._date_end = None
        self._date_modified = None
        self.discriminator = None

        if meal_plan_free_id is not None:
            self.meal_plan_free_id = meal_plan_free_id
        if record_type_enum is not None:
            self.record_type_enum = record_type_enum
        if meal_plan_id is not None:
            self.meal_plan_id = meal_plan_id
        if date_start is not None:
            self.date_start = date_start
        if date_end is not None:
            self.date_end = date_end
        if date_modified is not None:
            self.date_modified = date_modified

    @property
    def meal_plan_free_id(self):
        """Gets the meal_plan_free_id of this MealPlanFreeItem.  # noqa: E501

        Meal Plan Free  # noqa: E501

        :return: The meal_plan_free_id of this MealPlanFreeItem.  # noqa: E501
        :rtype: int
        """
        return self._meal_plan_free_id

    @meal_plan_free_id.setter
    def meal_plan_free_id(self, meal_plan_free_id):
        """Sets the meal_plan_free_id of this MealPlanFreeItem.

        Meal Plan Free  # noqa: E501

        :param meal_plan_free_id: The meal_plan_free_id of this MealPlanFreeItem.  # noqa: E501
        :type: int
        """

        self._meal_plan_free_id = meal_plan_free_id

    @property
    def record_type_enum(self):
        """Gets the record_type_enum of this MealPlanFreeItem.  # noqa: E501

        Record Type  # noqa: E501

        :return: The record_type_enum of this MealPlanFreeItem.  # noqa: E501
        :rtype: str
        """
        return self._record_type_enum

    @record_type_enum.setter
    def record_type_enum(self, record_type_enum):
        """Sets the record_type_enum of this MealPlanFreeItem.

        Record Type  # noqa: E501

        :param record_type_enum: The record_type_enum of this MealPlanFreeItem.  # noqa: E501
        :type: str
        """

        self._record_type_enum = record_type_enum

    @property
    def meal_plan_id(self):
        """Gets the meal_plan_id of this MealPlanFreeItem.  # noqa: E501

        Meal Plan  # noqa: E501

        :return: The meal_plan_id of this MealPlanFreeItem.  # noqa: E501
        :rtype: int
        """
        return self._meal_plan_id

    @meal_plan_id.setter
    def meal_plan_id(self, meal_plan_id):
        """Sets the meal_plan_id of this MealPlanFreeItem.

        Meal Plan  # noqa: E501

        :param meal_plan_id: The meal_plan_id of this MealPlanFreeItem.  # noqa: E501
        :type: int
        """

        self._meal_plan_id = meal_plan_id

    @property
    def date_start(self):
        """Gets the date_start of this MealPlanFreeItem.  # noqa: E501

        Date Start  # noqa: E501

        :return: The date_start of this MealPlanFreeItem.  # noqa: E501
        :rtype: str
        """
        return self._date_start

    @date_start.setter
    def date_start(self, date_start):
        """Sets the date_start of this MealPlanFreeItem.

        Date Start  # noqa: E501

        :param date_start: The date_start of this MealPlanFreeItem.  # noqa: E501
        :type: str
        """

        self._date_start = date_start

    @property
    def date_end(self):
        """Gets the date_end of this MealPlanFreeItem.  # noqa: E501

        Date End  # noqa: E501

        :return: The date_end of this MealPlanFreeItem.  # noqa: E501
        :rtype: str
        """
        return self._date_end

    @date_end.setter
    def date_end(self, date_end):
        """Sets the date_end of this MealPlanFreeItem.

        Date End  # noqa: E501

        :param date_end: The date_end of this MealPlanFreeItem.  # noqa: E501
        :type: str
        """

        self._date_end = date_end

    @property
    def date_modified(self):
        """Gets the date_modified of this MealPlanFreeItem.  # noqa: E501

        Date Modified  # noqa: E501

        :return: The date_modified of this MealPlanFreeItem.  # noqa: E501
        :rtype: str
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this MealPlanFreeItem.

        Date Modified  # noqa: E501

        :param date_modified: The date_modified of this MealPlanFreeItem.  # noqa: E501
        :type: str
        """

        self._date_modified = date_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MealPlanFreeItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
