# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PortalStepLinkItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'portal_step_link_id': 'int',
        'portal_step_id': 'int',
        'next_portal_step_id': 'int',
        'check_order': 'int',
        'record_type_enum': 'str',
        'date_created': 'datetime',
        'security_user_id': 'int',
        'date_modified': 'str'
    }

    attribute_map = {
        'portal_step_link_id': 'PortalStepLinkID',
        'portal_step_id': 'PortalStepID',
        'next_portal_step_id': 'Next_PortalStepID',
        'check_order': 'CheckOrder',
        'record_type_enum': 'RecordTypeEnum',
        'date_created': 'DateCreated',
        'security_user_id': 'SecurityUserID',
        'date_modified': 'DateModified'
    }

    def __init__(self, portal_step_link_id=None, portal_step_id=None, next_portal_step_id=None, check_order=None, record_type_enum=None, date_created=None, security_user_id=None, date_modified=None):  # noqa: E501
        """PortalStepLinkItem - a model defined in Swagger"""  # noqa: E501

        self._portal_step_link_id = None
        self._portal_step_id = None
        self._next_portal_step_id = None
        self._check_order = None
        self._record_type_enum = None
        self._date_created = None
        self._security_user_id = None
        self._date_modified = None
        self.discriminator = None

        if portal_step_link_id is not None:
            self.portal_step_link_id = portal_step_link_id
        if portal_step_id is not None:
            self.portal_step_id = portal_step_id
        if next_portal_step_id is not None:
            self.next_portal_step_id = next_portal_step_id
        if check_order is not None:
            self.check_order = check_order
        if record_type_enum is not None:
            self.record_type_enum = record_type_enum
        if date_created is not None:
            self.date_created = date_created
        if security_user_id is not None:
            self.security_user_id = security_user_id
        if date_modified is not None:
            self.date_modified = date_modified

    @property
    def portal_step_link_id(self):
        """Gets the portal_step_link_id of this PortalStepLinkItem.  # noqa: E501

        Portal Step Link  # noqa: E501

        :return: The portal_step_link_id of this PortalStepLinkItem.  # noqa: E501
        :rtype: int
        """
        return self._portal_step_link_id

    @portal_step_link_id.setter
    def portal_step_link_id(self, portal_step_link_id):
        """Sets the portal_step_link_id of this PortalStepLinkItem.

        Portal Step Link  # noqa: E501

        :param portal_step_link_id: The portal_step_link_id of this PortalStepLinkItem.  # noqa: E501
        :type: int
        """

        self._portal_step_link_id = portal_step_link_id

    @property
    def portal_step_id(self):
        """Gets the portal_step_id of this PortalStepLinkItem.  # noqa: E501

        Portal Step  # noqa: E501

        :return: The portal_step_id of this PortalStepLinkItem.  # noqa: E501
        :rtype: int
        """
        return self._portal_step_id

    @portal_step_id.setter
    def portal_step_id(self, portal_step_id):
        """Sets the portal_step_id of this PortalStepLinkItem.

        Portal Step  # noqa: E501

        :param portal_step_id: The portal_step_id of this PortalStepLinkItem.  # noqa: E501
        :type: int
        """

        self._portal_step_id = portal_step_id

    @property
    def next_portal_step_id(self):
        """Gets the next_portal_step_id of this PortalStepLinkItem.  # noqa: E501

        Next Portal Step  # noqa: E501

        :return: The next_portal_step_id of this PortalStepLinkItem.  # noqa: E501
        :rtype: int
        """
        return self._next_portal_step_id

    @next_portal_step_id.setter
    def next_portal_step_id(self, next_portal_step_id):
        """Sets the next_portal_step_id of this PortalStepLinkItem.

        Next Portal Step  # noqa: E501

        :param next_portal_step_id: The next_portal_step_id of this PortalStepLinkItem.  # noqa: E501
        :type: int
        """

        self._next_portal_step_id = next_portal_step_id

    @property
    def check_order(self):
        """Gets the check_order of this PortalStepLinkItem.  # noqa: E501

        Check Order  # noqa: E501

        :return: The check_order of this PortalStepLinkItem.  # noqa: E501
        :rtype: int
        """
        return self._check_order

    @check_order.setter
    def check_order(self, check_order):
        """Sets the check_order of this PortalStepLinkItem.

        Check Order  # noqa: E501

        :param check_order: The check_order of this PortalStepLinkItem.  # noqa: E501
        :type: int
        """

        self._check_order = check_order

    @property
    def record_type_enum(self):
        """Gets the record_type_enum of this PortalStepLinkItem.  # noqa: E501

        Record Type  # noqa: E501

        :return: The record_type_enum of this PortalStepLinkItem.  # noqa: E501
        :rtype: str
        """
        return self._record_type_enum

    @record_type_enum.setter
    def record_type_enum(self, record_type_enum):
        """Sets the record_type_enum of this PortalStepLinkItem.

        Record Type  # noqa: E501

        :param record_type_enum: The record_type_enum of this PortalStepLinkItem.  # noqa: E501
        :type: str
        """

        self._record_type_enum = record_type_enum

    @property
    def date_created(self):
        """Gets the date_created of this PortalStepLinkItem.  # noqa: E501

        Date Created  # noqa: E501

        :return: The date_created of this PortalStepLinkItem.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this PortalStepLinkItem.

        Date Created  # noqa: E501

        :param date_created: The date_created of this PortalStepLinkItem.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def security_user_id(self):
        """Gets the security_user_id of this PortalStepLinkItem.  # noqa: E501

        Security User  # noqa: E501

        :return: The security_user_id of this PortalStepLinkItem.  # noqa: E501
        :rtype: int
        """
        return self._security_user_id

    @security_user_id.setter
    def security_user_id(self, security_user_id):
        """Sets the security_user_id of this PortalStepLinkItem.

        Security User  # noqa: E501

        :param security_user_id: The security_user_id of this PortalStepLinkItem.  # noqa: E501
        :type: int
        """

        self._security_user_id = security_user_id

    @property
    def date_modified(self):
        """Gets the date_modified of this PortalStepLinkItem.  # noqa: E501

        Date Modified  # noqa: E501

        :return: The date_modified of this PortalStepLinkItem.  # noqa: E501
        :rtype: str
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this PortalStepLinkItem.

        Date Modified  # noqa: E501

        :param date_modified: The date_modified of this PortalStepLinkItem.  # noqa: E501
        :type: str
        """

        self._date_modified = date_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PortalStepLinkItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
