# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ReportSettingItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'report_setting_id': 'int',
        'report_id': 'int',
        'control_name': 'str',
        'setting_value': 'str',
        'date_modified': 'str'
    }

    attribute_map = {
        'report_setting_id': 'ReportSettingID',
        'report_id': 'ReportID',
        'control_name': 'ControlName',
        'setting_value': 'SettingValue',
        'date_modified': 'DateModified'
    }

    def __init__(self, report_setting_id=None, report_id=None, control_name=None, setting_value=None, date_modified=None):  # noqa: E501
        """ReportSettingItem - a model defined in Swagger"""  # noqa: E501

        self._report_setting_id = None
        self._report_id = None
        self._control_name = None
        self._setting_value = None
        self._date_modified = None
        self.discriminator = None

        if report_setting_id is not None:
            self.report_setting_id = report_setting_id
        if report_id is not None:
            self.report_id = report_id
        if control_name is not None:
            self.control_name = control_name
        if setting_value is not None:
            self.setting_value = setting_value
        if date_modified is not None:
            self.date_modified = date_modified

    @property
    def report_setting_id(self):
        """Gets the report_setting_id of this ReportSettingItem.  # noqa: E501

        Report Setting  # noqa: E501

        :return: The report_setting_id of this ReportSettingItem.  # noqa: E501
        :rtype: int
        """
        return self._report_setting_id

    @report_setting_id.setter
    def report_setting_id(self, report_setting_id):
        """Sets the report_setting_id of this ReportSettingItem.

        Report Setting  # noqa: E501

        :param report_setting_id: The report_setting_id of this ReportSettingItem.  # noqa: E501
        :type: int
        """

        self._report_setting_id = report_setting_id

    @property
    def report_id(self):
        """Gets the report_id of this ReportSettingItem.  # noqa: E501

        Report  # noqa: E501

        :return: The report_id of this ReportSettingItem.  # noqa: E501
        :rtype: int
        """
        return self._report_id

    @report_id.setter
    def report_id(self, report_id):
        """Sets the report_id of this ReportSettingItem.

        Report  # noqa: E501

        :param report_id: The report_id of this ReportSettingItem.  # noqa: E501
        :type: int
        """

        self._report_id = report_id

    @property
    def control_name(self):
        """Gets the control_name of this ReportSettingItem.  # noqa: E501

        Control Name  # noqa: E501

        :return: The control_name of this ReportSettingItem.  # noqa: E501
        :rtype: str
        """
        return self._control_name

    @control_name.setter
    def control_name(self, control_name):
        """Sets the control_name of this ReportSettingItem.

        Control Name  # noqa: E501

        :param control_name: The control_name of this ReportSettingItem.  # noqa: E501
        :type: str
        """
        if control_name is not None and len(control_name) > 1000:
            raise ValueError("Invalid value for `control_name`, length must be less than or equal to `1000`")  # noqa: E501

        self._control_name = control_name

    @property
    def setting_value(self):
        """Gets the setting_value of this ReportSettingItem.  # noqa: E501

        Setting Value  # noqa: E501

        :return: The setting_value of this ReportSettingItem.  # noqa: E501
        :rtype: str
        """
        return self._setting_value

    @setting_value.setter
    def setting_value(self, setting_value):
        """Sets the setting_value of this ReportSettingItem.

        Setting Value  # noqa: E501

        :param setting_value: The setting_value of this ReportSettingItem.  # noqa: E501
        :type: str
        """

        self._setting_value = setting_value

    @property
    def date_modified(self):
        """Gets the date_modified of this ReportSettingItem.  # noqa: E501

        Date Modified  # noqa: E501

        :return: The date_modified of this ReportSettingItem.  # noqa: E501
        :rtype: str
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this ReportSettingItem.

        Date Modified  # noqa: E501

        :param date_modified: The date_modified of this ReportSettingItem.  # noqa: E501
        :type: str
        """

        self._date_modified = date_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportSettingItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
