# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RoomBaseGenderItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'room_base_gender_id': 'int',
        'date_start': 'str',
        'date_end': 'str',
        'room_base_id': 'int',
        'gender_type_enum': 'str',
        'date_modified': 'str'
    }

    attribute_map = {
        'room_base_gender_id': 'RoomBaseGenderID',
        'date_start': 'DateStart',
        'date_end': 'DateEnd',
        'room_base_id': 'RoomBaseID',
        'gender_type_enum': 'GenderTypeEnum',
        'date_modified': 'DateModified'
    }

    def __init__(self, room_base_gender_id=None, date_start=None, date_end=None, room_base_id=None, gender_type_enum=None, date_modified=None):  # noqa: E501
        """RoomBaseGenderItem - a model defined in Swagger"""  # noqa: E501

        self._room_base_gender_id = None
        self._date_start = None
        self._date_end = None
        self._room_base_id = None
        self._gender_type_enum = None
        self._date_modified = None
        self.discriminator = None

        if room_base_gender_id is not None:
            self.room_base_gender_id = room_base_gender_id
        if date_start is not None:
            self.date_start = date_start
        if date_end is not None:
            self.date_end = date_end
        if room_base_id is not None:
            self.room_base_id = room_base_id
        if gender_type_enum is not None:
            self.gender_type_enum = gender_type_enum
        if date_modified is not None:
            self.date_modified = date_modified

    @property
    def room_base_gender_id(self):
        """Gets the room_base_gender_id of this RoomBaseGenderItem.  # noqa: E501

        Room Base Gender  # noqa: E501

        :return: The room_base_gender_id of this RoomBaseGenderItem.  # noqa: E501
        :rtype: int
        """
        return self._room_base_gender_id

    @room_base_gender_id.setter
    def room_base_gender_id(self, room_base_gender_id):
        """Sets the room_base_gender_id of this RoomBaseGenderItem.

        Room Base Gender  # noqa: E501

        :param room_base_gender_id: The room_base_gender_id of this RoomBaseGenderItem.  # noqa: E501
        :type: int
        """

        self._room_base_gender_id = room_base_gender_id

    @property
    def date_start(self):
        """Gets the date_start of this RoomBaseGenderItem.  # noqa: E501

        Date Start  # noqa: E501

        :return: The date_start of this RoomBaseGenderItem.  # noqa: E501
        :rtype: str
        """
        return self._date_start

    @date_start.setter
    def date_start(self, date_start):
        """Sets the date_start of this RoomBaseGenderItem.

        Date Start  # noqa: E501

        :param date_start: The date_start of this RoomBaseGenderItem.  # noqa: E501
        :type: str
        """

        self._date_start = date_start

    @property
    def date_end(self):
        """Gets the date_end of this RoomBaseGenderItem.  # noqa: E501

        Date End  # noqa: E501

        :return: The date_end of this RoomBaseGenderItem.  # noqa: E501
        :rtype: str
        """
        return self._date_end

    @date_end.setter
    def date_end(self, date_end):
        """Sets the date_end of this RoomBaseGenderItem.

        Date End  # noqa: E501

        :param date_end: The date_end of this RoomBaseGenderItem.  # noqa: E501
        :type: str
        """

        self._date_end = date_end

    @property
    def room_base_id(self):
        """Gets the room_base_id of this RoomBaseGenderItem.  # noqa: E501

        Room Base  # noqa: E501

        :return: The room_base_id of this RoomBaseGenderItem.  # noqa: E501
        :rtype: int
        """
        return self._room_base_id

    @room_base_id.setter
    def room_base_id(self, room_base_id):
        """Sets the room_base_id of this RoomBaseGenderItem.

        Room Base  # noqa: E501

        :param room_base_id: The room_base_id of this RoomBaseGenderItem.  # noqa: E501
        :type: int
        """

        self._room_base_id = room_base_id

    @property
    def gender_type_enum(self):
        """Gets the gender_type_enum of this RoomBaseGenderItem.  # noqa: E501

        Gender Type  # noqa: E501

        :return: The gender_type_enum of this RoomBaseGenderItem.  # noqa: E501
        :rtype: str
        """
        return self._gender_type_enum

    @gender_type_enum.setter
    def gender_type_enum(self, gender_type_enum):
        """Sets the gender_type_enum of this RoomBaseGenderItem.

        Gender Type  # noqa: E501

        :param gender_type_enum: The gender_type_enum of this RoomBaseGenderItem.  # noqa: E501
        :type: str
        """

        self._gender_type_enum = gender_type_enum

    @property
    def date_modified(self):
        """Gets the date_modified of this RoomBaseGenderItem.  # noqa: E501

        Date Modified  # noqa: E501

        :return: The date_modified of this RoomBaseGenderItem.  # noqa: E501
        :rtype: str
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this RoomBaseGenderItem.

        Date Modified  # noqa: E501

        :param date_modified: The date_modified of this RoomBaseGenderItem.  # noqa: E501
        :type: str
        """

        self._date_modified = date_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoomBaseGenderItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
