# coding: utf-8

"""
    StarRez API

    This is a way to connect with the StarRez API. We are not the developers of the StarRez API, we are just an organization that uses it and wanted a better way to connect to it.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: resdev@calpoly.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RoommateGroupItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'roommate_group_id': 'int',
        'record_type_enum': 'str',
        'description': 'str',
        'term_id': 'int',
        'entry_id': 'int',
        'verified': 'bool',
        'searchable': 'bool',
        'desired_group_size': 'int',
        'custom_bit1': 'bool',
        'custom_bit2': 'bool',
        'custom_string1': 'str',
        'custom_string2': 'str',
        'custom_string3': 'str',
        'custom_string4': 'str',
        'custom_string5': 'str',
        'custom_string6': 'str',
        'custom_date1': 'str',
        'custom_date2': 'str',
        'comments': 'str',
        'date_created': 'datetime',
        'date_modified': 'str'
    }

    attribute_map = {
        'roommate_group_id': 'RoommateGroupID',
        'record_type_enum': 'RecordTypeEnum',
        'description': 'Description',
        'term_id': 'TermID',
        'entry_id': 'EntryID',
        'verified': 'Verified',
        'searchable': 'Searchable',
        'desired_group_size': 'DesiredGroupSize',
        'custom_bit1': 'CustomBit1',
        'custom_bit2': 'CustomBit2',
        'custom_string1': 'CustomString1',
        'custom_string2': 'CustomString2',
        'custom_string3': 'CustomString3',
        'custom_string4': 'CustomString4',
        'custom_string5': 'CustomString5',
        'custom_string6': 'CustomString6',
        'custom_date1': 'CustomDate1',
        'custom_date2': 'CustomDate2',
        'comments': 'Comments',
        'date_created': 'DateCreated',
        'date_modified': 'DateModified'
    }

    def __init__(self, roommate_group_id=None, record_type_enum=None, description=None, term_id=None, entry_id=None, verified=None, searchable=None, desired_group_size=None, custom_bit1=None, custom_bit2=None, custom_string1=None, custom_string2=None, custom_string3=None, custom_string4=None, custom_string5=None, custom_string6=None, custom_date1=None, custom_date2=None, comments=None, date_created=None, date_modified=None):  # noqa: E501
        """RoommateGroupItem - a model defined in Swagger"""  # noqa: E501

        self._roommate_group_id = None
        self._record_type_enum = None
        self._description = None
        self._term_id = None
        self._entry_id = None
        self._verified = None
        self._searchable = None
        self._desired_group_size = None
        self._custom_bit1 = None
        self._custom_bit2 = None
        self._custom_string1 = None
        self._custom_string2 = None
        self._custom_string3 = None
        self._custom_string4 = None
        self._custom_string5 = None
        self._custom_string6 = None
        self._custom_date1 = None
        self._custom_date2 = None
        self._comments = None
        self._date_created = None
        self._date_modified = None
        self.discriminator = None

        if roommate_group_id is not None:
            self.roommate_group_id = roommate_group_id
        if record_type_enum is not None:
            self.record_type_enum = record_type_enum
        if description is not None:
            self.description = description
        if term_id is not None:
            self.term_id = term_id
        if entry_id is not None:
            self.entry_id = entry_id
        if verified is not None:
            self.verified = verified
        if searchable is not None:
            self.searchable = searchable
        if desired_group_size is not None:
            self.desired_group_size = desired_group_size
        if custom_bit1 is not None:
            self.custom_bit1 = custom_bit1
        if custom_bit2 is not None:
            self.custom_bit2 = custom_bit2
        if custom_string1 is not None:
            self.custom_string1 = custom_string1
        if custom_string2 is not None:
            self.custom_string2 = custom_string2
        if custom_string3 is not None:
            self.custom_string3 = custom_string3
        if custom_string4 is not None:
            self.custom_string4 = custom_string4
        if custom_string5 is not None:
            self.custom_string5 = custom_string5
        if custom_string6 is not None:
            self.custom_string6 = custom_string6
        if custom_date1 is not None:
            self.custom_date1 = custom_date1
        if custom_date2 is not None:
            self.custom_date2 = custom_date2
        if comments is not None:
            self.comments = comments
        if date_created is not None:
            self.date_created = date_created
        if date_modified is not None:
            self.date_modified = date_modified

    @property
    def roommate_group_id(self):
        """Gets the roommate_group_id of this RoommateGroupItem.  # noqa: E501

        Roommate Group  # noqa: E501

        :return: The roommate_group_id of this RoommateGroupItem.  # noqa: E501
        :rtype: int
        """
        return self._roommate_group_id

    @roommate_group_id.setter
    def roommate_group_id(self, roommate_group_id):
        """Sets the roommate_group_id of this RoommateGroupItem.

        Roommate Group  # noqa: E501

        :param roommate_group_id: The roommate_group_id of this RoommateGroupItem.  # noqa: E501
        :type: int
        """

        self._roommate_group_id = roommate_group_id

    @property
    def record_type_enum(self):
        """Gets the record_type_enum of this RoommateGroupItem.  # noqa: E501

        Record Type  # noqa: E501

        :return: The record_type_enum of this RoommateGroupItem.  # noqa: E501
        :rtype: str
        """
        return self._record_type_enum

    @record_type_enum.setter
    def record_type_enum(self, record_type_enum):
        """Sets the record_type_enum of this RoommateGroupItem.

        Record Type  # noqa: E501

        :param record_type_enum: The record_type_enum of this RoommateGroupItem.  # noqa: E501
        :type: str
        """

        self._record_type_enum = record_type_enum

    @property
    def description(self):
        """Gets the description of this RoommateGroupItem.  # noqa: E501

        Description  # noqa: E501

        :return: The description of this RoommateGroupItem.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this RoommateGroupItem.

        Description  # noqa: E501

        :param description: The description of this RoommateGroupItem.  # noqa: E501
        :type: str
        """
        if description is not None and len(description) > 50:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `50`")  # noqa: E501

        self._description = description

    @property
    def term_id(self):
        """Gets the term_id of this RoommateGroupItem.  # noqa: E501

        Term  # noqa: E501

        :return: The term_id of this RoommateGroupItem.  # noqa: E501
        :rtype: int
        """
        return self._term_id

    @term_id.setter
    def term_id(self, term_id):
        """Sets the term_id of this RoommateGroupItem.

        Term  # noqa: E501

        :param term_id: The term_id of this RoommateGroupItem.  # noqa: E501
        :type: int
        """

        self._term_id = term_id

    @property
    def entry_id(self):
        """Gets the entry_id of this RoommateGroupItem.  # noqa: E501

        Entry  # noqa: E501

        :return: The entry_id of this RoommateGroupItem.  # noqa: E501
        :rtype: int
        """
        return self._entry_id

    @entry_id.setter
    def entry_id(self, entry_id):
        """Sets the entry_id of this RoommateGroupItem.

        Entry  # noqa: E501

        :param entry_id: The entry_id of this RoommateGroupItem.  # noqa: E501
        :type: int
        """

        self._entry_id = entry_id

    @property
    def verified(self):
        """Gets the verified of this RoommateGroupItem.  # noqa: E501

        Verified  # noqa: E501

        :return: The verified of this RoommateGroupItem.  # noqa: E501
        :rtype: bool
        """
        return self._verified

    @verified.setter
    def verified(self, verified):
        """Sets the verified of this RoommateGroupItem.

        Verified  # noqa: E501

        :param verified: The verified of this RoommateGroupItem.  # noqa: E501
        :type: bool
        """

        self._verified = verified

    @property
    def searchable(self):
        """Gets the searchable of this RoommateGroupItem.  # noqa: E501

        Searchable  # noqa: E501

        :return: The searchable of this RoommateGroupItem.  # noqa: E501
        :rtype: bool
        """
        return self._searchable

    @searchable.setter
    def searchable(self, searchable):
        """Sets the searchable of this RoommateGroupItem.

        Searchable  # noqa: E501

        :param searchable: The searchable of this RoommateGroupItem.  # noqa: E501
        :type: bool
        """

        self._searchable = searchable

    @property
    def desired_group_size(self):
        """Gets the desired_group_size of this RoommateGroupItem.  # noqa: E501

        Desired Group Size  # noqa: E501

        :return: The desired_group_size of this RoommateGroupItem.  # noqa: E501
        :rtype: int
        """
        return self._desired_group_size

    @desired_group_size.setter
    def desired_group_size(self, desired_group_size):
        """Sets the desired_group_size of this RoommateGroupItem.

        Desired Group Size  # noqa: E501

        :param desired_group_size: The desired_group_size of this RoommateGroupItem.  # noqa: E501
        :type: int
        """

        self._desired_group_size = desired_group_size

    @property
    def custom_bit1(self):
        """Gets the custom_bit1 of this RoommateGroupItem.  # noqa: E501

        Custom Flag 1  # noqa: E501

        :return: The custom_bit1 of this RoommateGroupItem.  # noqa: E501
        :rtype: bool
        """
        return self._custom_bit1

    @custom_bit1.setter
    def custom_bit1(self, custom_bit1):
        """Sets the custom_bit1 of this RoommateGroupItem.

        Custom Flag 1  # noqa: E501

        :param custom_bit1: The custom_bit1 of this RoommateGroupItem.  # noqa: E501
        :type: bool
        """

        self._custom_bit1 = custom_bit1

    @property
    def custom_bit2(self):
        """Gets the custom_bit2 of this RoommateGroupItem.  # noqa: E501

        Custom Flag 2  # noqa: E501

        :return: The custom_bit2 of this RoommateGroupItem.  # noqa: E501
        :rtype: bool
        """
        return self._custom_bit2

    @custom_bit2.setter
    def custom_bit2(self, custom_bit2):
        """Sets the custom_bit2 of this RoommateGroupItem.

        Custom Flag 2  # noqa: E501

        :param custom_bit2: The custom_bit2 of this RoommateGroupItem.  # noqa: E501
        :type: bool
        """

        self._custom_bit2 = custom_bit2

    @property
    def custom_string1(self):
        """Gets the custom_string1 of this RoommateGroupItem.  # noqa: E501

        Custom String 1  # noqa: E501

        :return: The custom_string1 of this RoommateGroupItem.  # noqa: E501
        :rtype: str
        """
        return self._custom_string1

    @custom_string1.setter
    def custom_string1(self, custom_string1):
        """Sets the custom_string1 of this RoommateGroupItem.

        Custom String 1  # noqa: E501

        :param custom_string1: The custom_string1 of this RoommateGroupItem.  # noqa: E501
        :type: str
        """
        if custom_string1 is not None and len(custom_string1) > 50:
            raise ValueError("Invalid value for `custom_string1`, length must be less than or equal to `50`")  # noqa: E501

        self._custom_string1 = custom_string1

    @property
    def custom_string2(self):
        """Gets the custom_string2 of this RoommateGroupItem.  # noqa: E501

        Custom String 2  # noqa: E501

        :return: The custom_string2 of this RoommateGroupItem.  # noqa: E501
        :rtype: str
        """
        return self._custom_string2

    @custom_string2.setter
    def custom_string2(self, custom_string2):
        """Sets the custom_string2 of this RoommateGroupItem.

        Custom String 2  # noqa: E501

        :param custom_string2: The custom_string2 of this RoommateGroupItem.  # noqa: E501
        :type: str
        """
        if custom_string2 is not None and len(custom_string2) > 50:
            raise ValueError("Invalid value for `custom_string2`, length must be less than or equal to `50`")  # noqa: E501

        self._custom_string2 = custom_string2

    @property
    def custom_string3(self):
        """Gets the custom_string3 of this RoommateGroupItem.  # noqa: E501

        Custom String 3  # noqa: E501

        :return: The custom_string3 of this RoommateGroupItem.  # noqa: E501
        :rtype: str
        """
        return self._custom_string3

    @custom_string3.setter
    def custom_string3(self, custom_string3):
        """Sets the custom_string3 of this RoommateGroupItem.

        Custom String 3  # noqa: E501

        :param custom_string3: The custom_string3 of this RoommateGroupItem.  # noqa: E501
        :type: str
        """
        if custom_string3 is not None and len(custom_string3) > 50:
            raise ValueError("Invalid value for `custom_string3`, length must be less than or equal to `50`")  # noqa: E501

        self._custom_string3 = custom_string3

    @property
    def custom_string4(self):
        """Gets the custom_string4 of this RoommateGroupItem.  # noqa: E501

        Custom String 4  # noqa: E501

        :return: The custom_string4 of this RoommateGroupItem.  # noqa: E501
        :rtype: str
        """
        return self._custom_string4

    @custom_string4.setter
    def custom_string4(self, custom_string4):
        """Sets the custom_string4 of this RoommateGroupItem.

        Custom String 4  # noqa: E501

        :param custom_string4: The custom_string4 of this RoommateGroupItem.  # noqa: E501
        :type: str
        """
        if custom_string4 is not None and len(custom_string4) > 50:
            raise ValueError("Invalid value for `custom_string4`, length must be less than or equal to `50`")  # noqa: E501

        self._custom_string4 = custom_string4

    @property
    def custom_string5(self):
        """Gets the custom_string5 of this RoommateGroupItem.  # noqa: E501

        Custom String 5  # noqa: E501

        :return: The custom_string5 of this RoommateGroupItem.  # noqa: E501
        :rtype: str
        """
        return self._custom_string5

    @custom_string5.setter
    def custom_string5(self, custom_string5):
        """Sets the custom_string5 of this RoommateGroupItem.

        Custom String 5  # noqa: E501

        :param custom_string5: The custom_string5 of this RoommateGroupItem.  # noqa: E501
        :type: str
        """
        if custom_string5 is not None and len(custom_string5) > 50:
            raise ValueError("Invalid value for `custom_string5`, length must be less than or equal to `50`")  # noqa: E501

        self._custom_string5 = custom_string5

    @property
    def custom_string6(self):
        """Gets the custom_string6 of this RoommateGroupItem.  # noqa: E501

        Custom String 6  # noqa: E501

        :return: The custom_string6 of this RoommateGroupItem.  # noqa: E501
        :rtype: str
        """
        return self._custom_string6

    @custom_string6.setter
    def custom_string6(self, custom_string6):
        """Sets the custom_string6 of this RoommateGroupItem.

        Custom String 6  # noqa: E501

        :param custom_string6: The custom_string6 of this RoommateGroupItem.  # noqa: E501
        :type: str
        """
        if custom_string6 is not None and len(custom_string6) > 50:
            raise ValueError("Invalid value for `custom_string6`, length must be less than or equal to `50`")  # noqa: E501

        self._custom_string6 = custom_string6

    @property
    def custom_date1(self):
        """Gets the custom_date1 of this RoommateGroupItem.  # noqa: E501

        Custom Date 1  # noqa: E501

        :return: The custom_date1 of this RoommateGroupItem.  # noqa: E501
        :rtype: str
        """
        return self._custom_date1

    @custom_date1.setter
    def custom_date1(self, custom_date1):
        """Sets the custom_date1 of this RoommateGroupItem.

        Custom Date 1  # noqa: E501

        :param custom_date1: The custom_date1 of this RoommateGroupItem.  # noqa: E501
        :type: str
        """

        self._custom_date1 = custom_date1

    @property
    def custom_date2(self):
        """Gets the custom_date2 of this RoommateGroupItem.  # noqa: E501

        Custom Date 2  # noqa: E501

        :return: The custom_date2 of this RoommateGroupItem.  # noqa: E501
        :rtype: str
        """
        return self._custom_date2

    @custom_date2.setter
    def custom_date2(self, custom_date2):
        """Sets the custom_date2 of this RoommateGroupItem.

        Custom Date 2  # noqa: E501

        :param custom_date2: The custom_date2 of this RoommateGroupItem.  # noqa: E501
        :type: str
        """

        self._custom_date2 = custom_date2

    @property
    def comments(self):
        """Gets the comments of this RoommateGroupItem.  # noqa: E501

        Comments  # noqa: E501

        :return: The comments of this RoommateGroupItem.  # noqa: E501
        :rtype: str
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this RoommateGroupItem.

        Comments  # noqa: E501

        :param comments: The comments of this RoommateGroupItem.  # noqa: E501
        :type: str
        """
        if comments is not None and len(comments) > 200:
            raise ValueError("Invalid value for `comments`, length must be less than or equal to `200`")  # noqa: E501

        self._comments = comments

    @property
    def date_created(self):
        """Gets the date_created of this RoommateGroupItem.  # noqa: E501

        Date Created  # noqa: E501

        :return: The date_created of this RoommateGroupItem.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this RoommateGroupItem.

        Date Created  # noqa: E501

        :param date_created: The date_created of this RoommateGroupItem.  # noqa: E501
        :type: datetime
        """

        self._date_created = date_created

    @property
    def date_modified(self):
        """Gets the date_modified of this RoommateGroupItem.  # noqa: E501

        Date Modified  # noqa: E501

        :return: The date_modified of this RoommateGroupItem.  # noqa: E501
        :rtype: str
        """
        return self._date_modified

    @date_modified.setter
    def date_modified(self, date_modified):
        """Sets the date_modified of this RoommateGroupItem.

        Date Modified  # noqa: E501

        :param date_modified: The date_modified of this RoommateGroupItem.  # noqa: E501
        :type: str
        """

        self._date_modified = date_modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoommateGroupItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
