post:
  summary: ""
  operationId: updateApplicationStatus
  description: Updates an ApplicationStatus in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: path
      name: ApplicationStatusID
      type: integer
      required: true
      description: Numeric value of the applicationstatusID
    - in: body
      name: ApplicationStatusItem
      required: true
      description: ApplicationStatus to update
      schema:
        $ref: '#/definitions/ApplicationStatusItem'
  responses:
    200:
      description: Updated Item
      schema:
        type: array
        items:
          $ref: '#/definitions/ApplicationStatusItem'
    400:
      description: Invalid Input, Object Invalid.
