post:
  summary: ""
  operationId: updateEntryApplicationNote
  description: Updates an EntryApplicationNote in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: path
      name: EntryApplicationNoteID
      type: integer
      required: true
      description: Numeric value of the entryapplicationnoteID
    - in: body
      name: EntryApplicationNoteItem
      required: true
      description: EntryApplicationNote to update
      schema:
        $ref: '#/definitions/EntryApplicationNoteItem'
  responses:
    200:
      description: Updated Item
      schema:
        type: array
        items:
          $ref: '#/definitions/EntryApplicationNoteItem'
    400:
      description: Invalid Input, Object Invalid.