post:
  summary: ""
  operationId: updateEntryApplicationPreference
  description: Updates an EntryApplicationPreference in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: path
      name: EntryApplicationPreferenceID
      type: integer
      required: true
      description: Numeric value of the entryapplicationpreferenceID
    - in: body
      name: EntryApplicationPreferenceItem
      required: true
      description: EntryApplicationPreference to update
      schema:
        $ref: '#/definitions/EntryApplicationPreferenceItem'
  responses:
    200:
      description: Updated Item
      schema:
        type: array
        items:
          $ref: '#/definitions/EntryApplicationPreferenceItem'
    400:
      description: Invalid Input, Object Invalid.
