post:
  summary: ""
  operationId: updateInterfaceApplication
  description: Updates an InterfaceApplication in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: path
      name: InterfaceApplicationID
      type: integer
      required: true
      description: Numeric value of the interfaceapplicationID
    - in: body
      name: InterfaceApplicationItem
      required: true
      description: InterfaceApplication to update
      schema:
        $ref: '#/definitions/InterfaceApplicationItem'
  responses:
    200:
      description: Updated Item
      schema:
        type: array
        items:
          $ref: '#/definitions/InterfaceApplicationItem'
    400:
      description: Invalid Input, Object Invalid.
