post:
  summary: ""
  operationId: updateMessageSubscriptionSettings
  description: Updates an MessageSubscriptionSettings in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: path
      name: MessageSubscriptionSettingsID
      type: integer
      required: true
      description: Numeric value of the messagesubscriptionsettingsID
    - in: body
      name: MessageSubscriptionSettingsItem
      required: true
      description: MessageSubscriptionSettings to update
      schema:
        $ref: '#/definitions/MessageSubscriptionSettingsItem'
  responses:
    200:
      description: Updated Item
      schema:
        type: array
        items:
          $ref: '#/definitions/MessageSubscriptionSettingsItem'
    400:
      description: Invalid Input, Object Invalid.