post:
  summary: ""
  operationId: updateRoomConfiguration
  description: Updates an RoomConfiguration in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: path
      name: RoomConfigurationID
      type: integer
      required: true
      description: Numeric value of the roomconfigurationID
    - in: body
      name: RoomConfigurationItem
      required: true
      description: RoomConfiguration to update
      schema:
        $ref: '#/definitions/RoomConfigurationItem'
  responses:
    200:
      description: Updated Item
      schema:
        type: array
        items:
          $ref: '#/definitions/RoomConfigurationItem'
    400:
      description: Invalid Input, Object Invalid.