post:
  summary: ""
  operationId: updateRoomConfigurationClassification
  description: Updates an RoomConfigurationClassification in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: path
      name: RoomConfigurationClassificationID
      type: integer
      required: true
      description: Numeric value of the roomconfigurationclassificationID
    - in: body
      name: RoomConfigurationClassificationItem
      required: true
      description: RoomConfigurationClassification to update
      schema:
        $ref: '#/definitions/RoomConfigurationClassificationItem'
  responses:
    200:
      description: Updated Item
      schema:
        type: array
        items:
          $ref: '#/definitions/RoomConfigurationClassificationItem'
    400:
      description: Invalid Input, Object Invalid.
