post:
  summary: ""
  operationId: updateRoomConfigurationTermType
  description: Updates an RoomConfigurationTermType in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: path
      name: RoomConfigurationTermTypeID
      type: integer
      required: true
      description: Numeric value of the roomconfigurationtermtypeID
    - in: body
      name: RoomConfigurationTermTypeItem
      required: true
      description: RoomConfigurationTermType to update
      schema:
        $ref: '#/definitions/RoomConfigurationTermTypeItem'
  responses:
    200:
      description: Updated Item
      schema:
        type: array
        items:
          $ref: '#/definitions/RoomConfigurationTermTypeItem'
    400:
      description: Invalid Input, Object Invalid.
