post:
  summary: ""
  operationId: updateRoomConfigurationAttribute
  description: Updates an RoomConfigurationAttribute in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: path
      name: RoomConfigurationAttributeID
      type: integer
      required: true
      description: Numeric value of the roomconfigurationattributeID
    - in: body
      name: RoomConfigurationAttributeItem
      required: true
      description: RoomConfigurationAttribute to update
      schema:
        $ref: '#/definitions/RoomConfigurationAttributeItem'
  responses:
    200:
      description: Updated Item
      schema:
        type: array
        items:
          $ref: '#/definitions/RoomConfigurationAttributeItem'
    400:
      description: Invalid Input, Object Invalid.
