post:
  summary: ""
  operationId: updateRoomConfigurationProfile
  description: Updates an RoomConfigurationProfile in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: path
      name: RoomConfigurationProfileID
      type: integer
      required: true
      description: Numeric value of the roomconfigurationprofileID
    - in: body
      name: RoomConfigurationProfileItem
      required: true
      description: RoomConfigurationProfile to update
      schema:
        $ref: '#/definitions/RoomConfigurationProfileItem'
  responses:
    200:
      description: Updated Item
      schema:
        type: array
        items:
          $ref: '#/definitions/RoomConfigurationProfileItem'
    400:
      description: Invalid Input, Object Invalid.
