post:
  summary: ""
  operationId: updateWorkflow
  description: Updates an Workflow in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: path
      name: WorkflowID
      type: integer
      required: true
      description: Numeric value of the workflowID
    - in: body
      name: WorkflowItem
      required: true
      description: Workflow to update
      schema:
        $ref: '#/definitions/WorkflowItem'
  responses:
    200:
      description: Updated Item
      schema:
        type: array
        items:
          $ref: '#/definitions/WorkflowItem'
    400:
      description: Invalid Input, Object Invalid.