get:
  summary: ""
  operationId: searchApplicationStatus
  description: By passing in the appropriate options, you can search for a ApplicationStatus in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: ApplicationStatusID
      description: ID of the ApplicationStatus you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/ApplicationStatusItem'
    400:
      description: Bad Request
post:
  summary: ""
  operationId: searchApplicationStatusXML
  description: By passing in the appropriate xml, you can search for a ApplicationStatus in the system
  consumes:
    - application/xml
  produces:
    - application/json
  parameters:
    - in: body
      name: Query
      required: true
      description: An XML query on the ApplicationStatus table
      schema:
        type: string'
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/ApplicationStatusItem'
    400:
      description: Bad Request
