get:
  summary: ""
  operationId: searchEntryApplicationPreference
  description: By passing in the appropriate options, you can search for a EntryApplicationPreference in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: EntryApplicationPreferenceID
      description: ID of the EntryApplicationPreference you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/EntryApplicationPreferenceItem'
    400:
      description: Bad Request
post:
  summary: ""
  operationId: searchEntryApplicationPreferenceXML
  description: By passing in the appropriate xml, you can search for a EntryApplicationPreference in the system
  consumes:
    - application/xml
  produces:
    - application/json
  parameters:
    - in: body
      name: Query
      required: true
      description: An XML query on the EntryApplicationPreference table
      schema:
        type: string
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/EntryApplicationPreferenceItem'
    400:
      description: Bad Request
