get:
  summary: ""
  operationId: searchEntryApplicationNote
  description: By passing in the appropriate options, you can search for a EntryApplicationNote in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: EntryApplicationNoteID
      description: ID of the EntryApplicationNote you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/EntryApplicationNoteItem'
    400:
      description: Bad Request
post:
  summary: ""
  operationId: searchEntryApplicationNoteXML
  description: By passing in the appropriate xml, you can search for a EntryApplicationNote in the system
  consumes:
    - application/xml
  produces:
    - application/json
  parameters:
    - in: body
      name: Query
      required: true
      description: An XML query on the EntryApplicationNote table
      schema:
        type: string
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/EntryApplicationNoteItem'
    400:
      description: Bad Request
