get:
  summary: ""
  operationId: searchEntryApplicationRoomPreference
  description: By passing in the appropriate options, you can search for a EntryApplicationRoomPreference in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: EntryApplicationRoomPreferenceID
      description: ID of the EntryApplicationRoomPreference you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/EntryApplicationRoomPreferenceItem'
    400:
      description: Bad Request