get:
  summary: ""
  operationId: searchEntryApplicationCustomField
  description: By passing in the appropriate options, you can search for a EntryApplicationCustomField in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: EntryApplicationCustomFieldID
      description: ID of the EntryApplicationCustomField you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/EntryApplicationCustomFieldItem'
    400:
      description: Bad Request