get:
  summary: ""
  operationId: searchEntryApplicationPortalSection
  description: By passing in the appropriate options, you can search for a EntryApplicationPortalSection in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: EntryApplicationPortalSectionID
      description: ID of the EntryApplicationPortalSection you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/EntryApplicationPortalSectionItem'
    400:
      description: Bad Request