get:
  summary: ""
  operationId: searchEntryApplication
  description: By passing in the appropriate options, you can search for a EntryApplication in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: EntryApplicationID
      description: ID of the EntryApplication you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/EntryApplicationItem'
    400:
      description: Bad Request