get:
  summary: ""
  operationId: searchEntryApplicationRoomMate
  description: By passing in the appropriate options, you can search for a EntryApplicationRoomMate in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: EntryApplicationRoomMateID
      description: ID of the EntryApplicationRoomMate you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/EntryApplicationRoomMateItem'
    400:
      description: Bad Request
post:
  summary: ""
  operationId: searchEntryApplicationRoomMateXML
  description: By passing in the appropriate xml, you can search for a EntryApplicationRoomMate in the system
  consumes:
    - application/xml
  produces:
    - application/json
  parameters:
    - in: body
      name: Query
      required: true
      description: An XML query on the EntryApplicationRoomMate table
      schema:
        type: string
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/EntryApplicationRoomMateItem'
    400:
      description: Bad Request
