get:
  summary: ""
  operationId: searchInterfaceApplication
  description: By passing in the appropriate options, you can search for a InterfaceApplication in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: InterfaceApplicationID
      description: ID of the InterfaceApplication you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/InterfaceApplicationItem'
    400:
      description: Bad Request
post:
  summary: ""
  operationId: searchInterfaceApplicationXML
  description: By passing in the appropriate xml, you can search for a InterfaceApplication in the system
  consumes:
    - application/xml
  produces:
    - application/json
  parameters:
    - in: body
      name: Query
      required: true
      description: An XML query on the InterfaceApplication table
      schema:
        type: string'
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/InterfaceApplicationItem'
    400:
      description: Bad Request
