get:
  summary: ""
  operationId: searchMessageSubscriptionSettings
  description: By passing in the appropriate options, you can search for a MessageSubscriptionSettings in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: MessageSubscriptionSettingsID
      description: ID of the MessageSubscriptionSettings you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/MessageSubscriptionSettingsItem'
    400:
      description: Bad Request