get:
  summary: ""
  operationId: searchRefundRequestBatchConfigurationItem
  description: By passing in the appropriate options, you can search for a RefundRequestBatchConfigurationItem in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: RefundRequestBatchConfigurationItemID
      description: ID of the RefundRequestBatchConfigurationItem you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RefundRequestBatchConfigurationItemItem'
    400:
      description: Bad Request
post:
  summary: ""
  operationId: searchRefundRequestBatchConfigurationItemXML
  description: By passing in the appropriate xml, you can search for a RefundRequestBatchConfigurationItem in the system
  consumes:
    - application/xml
  produces:
    - application/json
  parameters:
    - in: body
      name: Query
      required: true
      description: An XML query on the RefundRequestBatchConfigurationItem table
      schema:
        type: string'
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RefundRequestBatchConfigurationItemItem'
    400:
      description: Bad Request
