get:
  summary: ""
  operationId: searchRefundRequestBatchConfiguration
  description: By passing in the appropriate options, you can search for a RefundRequestBatchConfiguration in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: RefundRequestBatchConfigurationID
      description: ID of the RefundRequestBatchConfiguration you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RefundRequestBatchConfigurationItem'
    400:
      description: Bad Request