get:
  summary: ""
  operationId: searchRefundRequestConfigurationBreakUp
  description: By passing in the appropriate options, you can search for a RefundRequestConfigurationBreakUp in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: RefundRequestConfigurationBreakUpID
      description: ID of the RefundRequestConfigurationBreakUp you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RefundRequestConfigurationBreakUpItem'
    400:
      description: Bad Request
post:
  summary: ""
  operationId: searchRefundRequestConfigurationBreakUpXML
  description: By passing in the appropriate xml, you can search for a RefundRequestConfigurationBreakUp in the system
  consumes:
    - application/xml
  produces:
    - application/json
  parameters:
    - in: body
      name: Query
      required: true
      description: An XML query on the RefundRequestConfigurationBreakUp table
      schema:
        type: string'
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RefundRequestConfigurationBreakUpItem'
    400:
      description: Bad Request
