get:
  summary: ""
  operationId: searchRefundRequestConfiguration
  description: By passing in the appropriate options, you can search for a RefundRequestConfiguration in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: RefundRequestConfigurationID
      description: ID of the RefundRequestConfiguration you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RefundRequestConfigurationItem'
    400:
      description: Bad Request
post:
  summary: ""
  operationId: searchRefundRequestConfigurationXML
  description: By passing in the appropriate xml, you can search for a RefundRequestConfiguration in the system
  consumes:
    - application/xml
  produces:
    - application/json
  parameters:
    - in: body
      name: Query
      required: true
      description: An XML query on the RefundRequestConfiguration table
      schema:
        type: string'
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RefundRequestConfigurationItem'
    400:
      description: Bad Request
