get:
  summary: ""
  operationId: searchRoomConfigurationTermType
  description: By passing in the appropriate options, you can search for a RoomConfigurationTermType in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: RoomConfigurationTermTypeID
      description: ID of the RoomConfigurationTermType you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RoomConfigurationTermTypeItem'
    400:
      description: Bad Request