get:
  summary: ""
  operationId: searchRoomConfiguration
  description: By passing in the appropriate options, you can search for a RoomConfiguration in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: RoomConfigurationID
      description: ID of the RoomConfiguration you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RoomConfigurationItem'
    400:
      description: Bad Request
post:
  summary: ""
  operationId: searchRoomConfigurationXML
  description: By passing in the appropriate xml, you can search for a RoomConfiguration in the system
  consumes:
    - application/xml
  produces:
    - application/json
  parameters:
    - in: body
      name: Query
      required: true
      description: An XML query on the RoomConfiguration table
      schema:
        type: string
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RoomConfigurationItem'
    400:
      description: Bad Request
