get:
  summary: ""
  operationId: searchRoomConfigurationRoomSort
  description: By passing in the appropriate options, you can search for a RoomConfigurationRoomSort in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: RoomConfigurationRoomSortID
      description: ID of the RoomConfigurationRoomSort you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RoomConfigurationRoomSortItem'
    400:
      description: Bad Request