get:
  summary: ""
  operationId: searchRoomConfigurationProfile
  description: By passing in the appropriate options, you can search for a RoomConfigurationProfile in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: RoomConfigurationProfileID
      description: ID of the RoomConfigurationProfile you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RoomConfigurationProfileItem'
    400:
      description: Bad Request