get:
  summary: ""
  operationId: searchRoomConfigurationAttribute
  description: By passing in the appropriate options, you can search for a RoomConfigurationAttribute in the system
  consumes:
    - application/json
    - application/xml
  produces:
    - application/json
  parameters:
    - in: query
      name: RoomConfigurationAttributeID
      description: ID of the RoomConfigurationAttribute you want to look up
      required: false
      type: integer
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RoomConfigurationAttributeItem'
    400:
      description: Bad Request
post:
  summary: ""
  operationId: searchRoomConfigurationAttributeXML
  description: By passing in the appropriate xml, you can search for a RoomConfigurationAttribute in the system
  consumes:
    - application/xml
  produces:
    - application/json
  parameters:
    - in: body
      name: Query
      required: true
      description: An XML query on the RoomConfigurationAttribute table
      schema:
        type: string'
  responses:
    200:
      description: Search results matching criteria.
      schema:
        type: array
        items:
          $ref: '#/definitions/RoomConfigurationAttributeItem'
    400:
      description: Bad Request
